# Generated by Django 4.2.2 on 2023-06-17 09:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='custome',
            fields=[
                ('id_cust', models.UUIDField(default=uuid.uuid5, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('N', "Don't Choose")], max_length=1)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone_num', models.IntegerField(blank=True, max_length=15, null=True)),
                ('birthday', models.DateField()),
                ('age', models.IntegerField(blank=True)),
                ('date_join', models.DateTimeField(auto_now_add=True)),
                ('edit_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
