# Generated by Django 4.2.2 on 2023-06-17 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custome',
            name='phone_num',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
