# Generated by Django 4.2.2 on 2023-06-17 10:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('store_apps', '0002_alter_custome_phone_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id_cust', models.UUIDField(default=uuid.uuid5, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='custome',
        ),
    ]
