# Generated by Django 4.2.2 on 2023-06-17 10:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store_apps', '0005_alter_customer_id_cust'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='birthday',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='date_join',
            field=models.DateField(default=django.utils.timezone.now, editable=False),
        ),
    ]
