# Generated by Django 4.2.2 on 2023-06-17 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_apps', '0006_alter_customer_age_alter_customer_birthday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_num',
            field=models.IntegerField(blank=True, max_length=15, null=True),
        ),
    ]
