# Generated by Django 4.2.2 on 2023-06-17 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_apps', '0007_alter_customer_age_alter_customer_phone_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone_num',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
