# Generated by Django 4.2.2 on 2023-06-17 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_apps', '0009_alter_customer_last_name_alter_customer_middle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='id_cust',
            field=models.BigAutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
