# Generated by Django 4.2.2 on 2023-06-17 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_apps', '0010_alter_customer_id_cust'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='id_cust',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
