# Generated by Django 4.2.2 on 2023-06-17 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_apps', '0011_alter_customer_id_cust'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='age',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
