# Generated by Django 4.2.2 on 2023-06-17 11:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('store_apps', '0012_alter_customer_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='id_cust',
            field=models.BigAutoField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
