# Generated by Django 4.2.2 on 2023-06-17 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_apps', '0014_alter_customer_id_cust'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='id_cust',
            new_name='d_cust',
        ),
    ]
