# Generated by Django 4.2.2 on 2023-06-17 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_apps', '0015_rename_id_cust_customer_d_cust'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='d_cust',
            new_name='id_cust',
        ),
    ]
