# Generated by Django 4.2.2 on 2023-06-17 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_apps', '0016_rename_d_cust_customer_id_cust'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='middle_name',
        ),
        migrations.AddField(
            model_name='customer',
            name='mmiddle_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
