# Generated by Django 4.2.2 on 2023-06-17 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_apps', '0017_remove_customer_middle_name_customer_mmiddle_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='mmiddle_name',
            new_name='middle_name',
        ),
    ]
