# Generated by Django 4.2.2 on 2023-06-17 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_apps', '0018_rename_mmiddle_name_customer_middle_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='id_cust',
        ),
        migrations.AddField(
            model_name='customer',
            name='cust',
            field=models.IntegerField(default=1, editable=False, primary_key=True, serialize=False),
        ),
    ]
