# Generated by Django 4.2.2 on 2023-06-17 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_apps', '0019_remove_customer_id_cust_customer_cust'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cust',
            field=models.IntegerField(editable=False, primary_key=True, serialize=False),
        ),
    ]
