# Generated by Django 4.2.2 on 2023-06-17 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_apps', '0020_alter_customer_cust'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='cust',
            new_name='cust_no',
        ),
    ]
