# Generated by Django 4.2.2 on 2023-06-17 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_apps', '0023_alter_customer_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='middle_name',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
