# Generated by Django 4.2.2 on 2023-06-17 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_apps', '0026_alter_customer_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='birthday',
            field=models.DateField(),
        ),
    ]
