# Generated by Django 4.2.2 on 2023-06-17 15:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store_apps', '0028_alter_customer_age_alter_customer_id_cust'),
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('-', 'N/A'), ('A', 'Electornics')], default='-', max_length=1)),
                ('cost', models.BooleanField(default=0)),
                ('desc', models.CharField(blank=True, max_length=100000, null=True)),
                ('date_add', models.DateField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
    ]
