# Generated by Django 4.2.2 on 2023-06-17 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_apps', '0033_alter_item_code_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='code_item',
            field=models.CharField(editable=False, max_length=10, primary_key=True, serialize=False),
        ),
    ]
