# Generated by Django 4.2.4 on 2023-08-09 11:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_apps', '0035_rename_code_item_item_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='code',
            field=models.CharField(editable=False, max_length=10000, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=100, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('0', 'N/A'), ('A', 'A'), ('B', 'B'), ('C', 'C')], default='0', max_length=1),
        ),
    ]
