# Generated by Django 4.2.4 on 2023-08-09 11:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store_apps', '0037_alter_customer_id_cust'),
    ]

    operations = [
        migrations.CreateModel(
            name='employees',
            fields=[
                ('id_emp', models.PositiveIntegerField(default='E1', editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, default='', max_length=50)),
                ('last_name', models.CharField(blank=True, default='', max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('N', "Don't Choose")], default='N', max_length=1)),
                ('job_title', models.CharField(choices=[('A', '!'), ('B', '2')], max_length=3)),
                ('placement', models.CharField(choices=[('A', '!'), ('B', '2')], max_length=3)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone_num', models.IntegerField(blank=True, null=True)),
                ('address', models.CharField(default='', max_length=100)),
                ('birthday', models.DateField()),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.CharField(choices=[(1, 'Active'), (0, 'Non-Active')], max_length=1)),
                ('date_join', models.DateField(default=django.utils.timezone.now, editable=False)),
                ('edit_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.CharField(default='', max_length=100),
        ),
    ]
