# Generated by Django 4.2.4 on 2023-08-09 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_apps', '0038_employees_customer_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='item',
        ),
    ]
