# Generated by Django 4.2.4 on 2023-08-09 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_apps', '0040_inventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='suplier',
            fields=[
                ('code', models.CharField(editable=False, max_length=100, primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=100)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='employees',
            old_name='phone_num',
            new_name='phone',
        ),
    ]
