# Generated by Django 4.2.2 on 2023-08-10 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_apps', '0041_suplier_rename_phone_num_employees_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='code',
            new_name='id_inventory',
        ),
        migrations.RenameField(
            model_name='suplier',
            old_name='code',
            new_name='id_suplier',
        ),
        migrations.AlterField(
            model_name='customer',
            name='id_cust',
            field=models.CharField(default='C1', editable=False, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employees',
            name='id_emp',
            field=models.CharField(default='E1', editable=False, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employees',
            name='is_active',
            field=models.CharField(choices=[('1', 'Active'), ('0', 'Non-Active')], max_length=1),
        ),
        migrations.AlterField(
            model_name='employees',
            name='placement',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=3),
        ),
    ]
