# Generated by Django 4.2.2 on 2023-08-10 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_apps', '0042_rename_code_inventory_id_inventory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='id_inventory',
            field=models.CharField(editable=False, max_length=100, primary_key=True, serialize=False),
        ),
    ]
