# Generated by Django 4.2.2 on 2023-08-10 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_apps', '0043_alter_inventory_id_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suplier',
            name='id_suplier',
            field=models.CharField(default='S1', editable=False, max_length=100, primary_key=True, serialize=False),
        ),
    ]
