# Generated by Django 4.2.2 on 2023-08-11 06:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store_apps', '0044_alter_suplier_id_suplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='inventory_in',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_qty', models.IntegerField()),
                ('date_in', models.DateField(default=django.utils.timezone.now, editable=False)),
                ('id_inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_apps.inventory')),
            ],
        ),
    ]
