# Generated by Django 4.2.2 on 2023-08-11 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store_apps', '0045_inventory_in'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone', models.BigIntegerField(blank=True, null=True)),
                ('address', models.CharField(default='', max_length=100)),
                ('birthday', models.DateField()),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='inventory_out',
            fields=[
                ('id_inventory', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='store_apps.inventory')),
                ('qty', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='inventory_stock',
            fields=[
                ('id_inventory', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='store_apps.inventory')),
                ('qty', models.PositiveIntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='inventory_in',
            old_name='in_qty',
            new_name='qty',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='age',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='phone_num',
        ),
        migrations.RemoveField(
            model_name='inventory_in',
            name='id',
        ),
        migrations.AlterField(
            model_name='inventory_in',
            name='id_inventory',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='store_apps.inventory'),
        ),
    ]
