# Generated by Django 4.2.2 on 2023-08-11 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_apps', '0046_contact_inventory_out_inventory_stock_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact',
            new_name='customer_information',
        ),
    ]
