# Generated by Django 4.2.2 on 2023-08-14 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_apps', '0048_contact_delete_customer_information_customer_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='cus_info',
        ),
    ]
