# Generated by Django 4.2.2 on 2023-08-14 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_apps', '0049_rename_contact_cus_info'),
    ]

    operations = [
        migrations.DeleteModel(
            name='inventory_stock',
        ),
    ]
