# Generated by Django 4.2.2 on 2023-08-15 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store_apps', '0050_delete_inventory_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='inventory_stock',
            fields=[
                ('id_inventory', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='store_apps.inventory')),
                ('qty', models.PositiveIntegerField()),
            ],
        ),
    ]
