# Generated by Django 4.2.2 on 2023-08-15 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_apps', '0051_inventory_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory_stock',
            name='qty',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
