# Generated by Django 4.2.2 on 2023-08-18 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_apps', '0052_alter_inventory_stock_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory_in',
            name='qty',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='inventory_out',
            name='qty',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='inventory_stock',
            name='qty',
            field=models.PositiveIntegerField(),
        ),
    ]
