# Generated by Django 4.2.2 on 2023-08-18 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_apps', '0053_alter_inventory_in_qty_alter_inventory_out_qty_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory_out',
            name='id_inventory',
        ),
        migrations.RemoveField(
            model_name='inventory_stock',
            name='id_inventory',
        ),
        migrations.DeleteModel(
            name='inventory_in',
        ),
        migrations.DeleteModel(
            name='inventory_out',
        ),
        migrations.DeleteModel(
            name='inventory_stock',
        ),
    ]
