# Generated by Django 4.2.2 on 2023-09-02 08:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store_apps', '0054_remove_inventory_out_id_inventory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryIn',
            fields=[
                ('inventory', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='store_apps.inventory')),
                ('qty', models.PositiveIntegerField(editable=False)),
                ('detein', models.DateField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryOut',
            fields=[
                ('inventory', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='store_apps.inventory')),
                ('qty', models.PositiveIntegerField(editable=False)),
                ('dateout', models.DateField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryStock',
            fields=[
                ('inventory', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='store_apps.inventory')),
                ('qty', models.PositiveIntegerField(editable=False)),
            ],
        ),
    ]
