# Generated by Django 4.2.2 on 2023-09-02 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_apps', '0055_inventoryin_inventoryout_inventorystock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryin',
            name='qty',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='inventoryout',
            name='qty',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
