# Generated by Django 4.2.2 on 2023-09-02 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_apps', '0057_inventoryin_id_inventoryout_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryin',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='inventoryout',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
