# Generated by Django 4.2.2 on 2023-09-02 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_apps', '0058_alter_inventoryin_id_alter_inventoryout_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorystock',
            name='qty',
            field=models.PositiveIntegerField(),
        ),
    ]
