# Generated by Django 4.2.4 on 2023-10-01 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_apps', '0060_inventoryin_sequence_inventoryout_sequence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryin',
            name='sequence',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
